// client/src/pages/GenrePage.tsx
import { useEffect, useState } from 'react';
import { useSearchParams, useParams, Link } from 'react-router';

import Loader from '../components/Loader';
import StateFromLink from '../components/StateFromLink';
import { GenreDto } from '../dtos/genre/GenreDto';
import { useReactRouterStateFrom } from '../hooks';
import GenreService from '../services/GenreService';

const GenrePage = () => {
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);
  const { id } = useParams();
  const [searchParams, setSearchParams] = useSearchParams();
  const from = useReactRouterStateFrom('/genres');
  const isEditMode = searchParams.get('edit') !== null;

  const [genre, setGenre] = useState<GenreDto>({} as GenreDto);

  const [name, setName] = useState('');

  const fetchGenre = (id: string) => {
    setError(false);
    setLoading(true);
    GenreService.getById(id)
      .then((response) => {
        setGenre(response.data);
        setName(response.data.name);
      })
      .catch(() => {
        setError(true);
      })
      .finally(() => {
        setLoading(false);
      });
  };

  useEffect(() => {
    if (id) {
      fetchGenre(id);
    }
  }, [id]);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!genre) return;

    const response = await GenreService.update(genre.id, { name });
    setGenre(response.data);
    setName(response.data.name);
    searchParams.delete('edit');
    setSearchParams(searchParams);
  };

  if (loading)
    <div className="flex justify-center mt-5">
      <Loader />
    </div>;

  return (
    <div className="max-w-5xl mx-auto p-6">
      <div className="bg-white p-6 rounded-lg shadow-md">
        <h2 className="text-2xl font-semibold text-gray-700">Информация о жанре</h2>
        {error ? (
          <div className="flex bg-red-100 text-red-500 font-semibold p-4 rounded-lg">
            Ошибка загрузки данных
          </div>
        ) : (
          <>
            {!isEditMode ? (
              <div className="mt-4">
                <p>
                  <strong>Название:</strong> {genre.name}
                </p>
                <div className="mt-6 flex gap-4">
                  <StateFromLink
                    to={`?edit`}
                    className="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600"
                  >
                    Редактировать
                  </StateFromLink>
                  <Link
                    to={from}
                    className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700"
                  >
                    Назад
                  </Link>
                </div>
              </div>
            ) : (
              <form onSubmit={handleSave} className="mt-4">
                <div className="mb-4">
                  <label htmlFor="name" className="block text-gray-700">
                    Название
                  </label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    className="mt-2 p-2 border border-gray-300 rounded-lg w-full"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    required
                  />
                </div>
                <div className="flex gap-4">
                  <button
                    type="submit"
                    className="bg-sky-400 text-white px-4 py-2 rounded hover:bg-sky-500"
                  >
                    Сохранить
                  </button>
                  <Link
                    to={from}
                    className="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700"
                  >
                    Отмена
                  </Link>
                </div>
              </form>
            )}
          </>
        )}
      </div>
    </div>
  );
};

export default GenrePage;

// client/src/app/features/genre/components/genre-page/genre-page.component.ts
import { NgIf, NgTemplateOutlet } from '@angular/common';
import { Component, TemplateRef, ViewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  ActivatedRoute,
  NavigationEnd,
  Router,
  RouterLink,
} from '@angular/router';
import { filter } from 'rxjs';
import { RouterStateFromType } from '../../../../core/models/router-state-from.model';
import { RouterStateService } from '../../../../core/services/route-state.service';
import { LoaderComponent } from '../../../../shared/components/loader/loader.component';
import { Genre } from '../../models/genre.model';
import { GenreService } from '../../services/genre.service';

@Component({
  selector: 'app-genre-page',
  imports: [NgIf, LoaderComponent, FormsModule, NgTemplateOutlet, RouterLink],
  templateUrl: './genre-page.component.html',
})
export class GenrePageComponent {
  readonly DEFAULT_BACK_URL = '/genres';

  genre: Genre = {} as Genre;
  name: string = '';
  error: boolean = false;
  loading: boolean = false;
  isEditMode: boolean = false;
  routerEditLinkState: {
    from: RouterStateFromType;
  };
  backUrl: RouterStateFromType;

  @ViewChild('viewTemplate', { static: true })
  viewTemplate!: TemplateRef<any>;

  @ViewChild('editTemplate', { static: true })
  editTemplate!: TemplateRef<any>;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private genreService: GenreService,
    private routerStateService: RouterStateService
  ) {
    this.routerEditLinkState = { from: { path: this.DEFAULT_BACK_URL } };
    this.backUrl = history.state?.from || { path: this.DEFAULT_BACK_URL };
  }

  ngOnInit() {
    this.route.paramMap.subscribe((params) => {
      const id = params.get('id');
      if (id) this.loadGenre(id);
    });

    this.route.queryParamMap.subscribe((queryParams) => {
      this.isEditMode = queryParams.has('edit');
    });

    this.routerStateService.routerState.subscribe((state) => {
      if (state) {
        this.routerEditLinkState.from = state;
      }
    });

    this.router.events
      .pipe(filter((e) => e instanceof NavigationEnd))
      .subscribe(() => {
        this.backUrl = history.state?.from || { path: this.DEFAULT_BACK_URL };
      });
  }

  loadGenre(id: string) {
    this.error = false;
    this.loading = true;
    this.genreService.getById(id).subscribe({
      next: (response) => {
        this.genre = response;
        this.name = response.name;
      },
      error: () => {
        this.error = true;
      },
      complete: () => {
        this.loading = false;
      },
    });
  }

  saveGenre() {
    if (!this.genre) return;

    this.genreService
      .update(this.genre.id, { name: this.name })
      .subscribe((response) => {
        this.genre = response;
        this.name = response.name;
        this.router.navigate([], { queryParams: {} });
      });
  }

  getCurrentTemplate() {
    return this.isEditMode ? this.editTemplate : this.viewTemplate;
  }
}

<div class="max-w-5xl mx-auto p-6">
  <div class="bg-white p-6 rounded-lg shadow-md">
    <h2 class="text-2xl font-semibold text-gray-700">Информация о жанре</h2>

    <div *ngIf="loading" class="flex justify-center mt-5">
      <app-loader></app-loader>
    </div>

    <div
      *ngIf="error"
      class="flex bg-red-100 text-red-500 font-semibold p-4 rounded-lg"
    >
      Ошибка загрузки данных
    </div>

    <ng-container *ngIf="!loading && !error">
      <ng-template
        [ngTemplateOutlet]="getCurrentTemplate()"
        [ngTemplateOutletContext]="{ genre: genre }"
      >
      </ng-template>
    </ng-container>
  </div>
</div>

<ng-template #viewTemplate>
  <p><strong>Название:</strong> {{ genre.name }}</p>
  <div class="mt-6 flex gap-4">
    <a
      [routerLink]="[]"
      [queryParams]="{ edit: '' }"
      [state]="routerEditLinkState"
      class="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600"
    >
      Редактировать
    </a>
    <a
      [routerLink]="backUrl.path"
      [queryParams]="backUrl.queryParams"
      [fragment]="backUrl.fragment"
      class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700"
    >
      Назад
    </a>
  </div>
</ng-template>

<ng-template #editTemplate>
  <form (ngSubmit)="saveGenre()" class="mt-4">
    <div class="mb-4">
      <label for="name" class="block text-gray-700">Название</label>
      <input
        type="text"
        id="name"
        name="name"
        class="mt-2 p-2 border border-gray-300 rounded-lg w-full"
        [(ngModel)]="name"
        required
      />
    </div>
    <div class="flex gap-4">
      <button
        type="submit"
        class="bg-sky-400 text-white px-4 py-2 rounded hover:bg-sky-500"
      >
        Сохранить
      </button>
      <a
        [routerLink]="backUrl.path"
        [queryParams]="backUrl.queryParams"
        [fragment]="backUrl.fragment"
        class="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700"
      >
        Отмена
      </a>
    </div>
  </form>
</ng-template>
